Fixing exception in _OnSensorAlarm due to unknown events from climate sensor
I have a dongle with HMS firmware and paired with a climate sensor.
The service will stop recieving any events after a while and it
turned out the event from climate sensor triggers the "unknown type"
path and causing exceptions:

```
Trying to parse: b'55aa531d1900000193e7c6c812a1373743363831443007115a00010059ae4608c8'
Received: b'55aa531d1900000193e7c6c812a1373743363831443007115a00010059ae4608c8'
<=== Received: Packet: Cmd=5319, Payload=b'00000193e7c6c812a1373743363831443007115a00010059ae46'
Sending ACK packet for cmd 5319
===> Sending: Packet: Cmd=53FF, Payload=ACK(5319)
Sending: b'aa555319ff026a'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/wyzesense2mqtt/wyzesense.py", line 413, in _Worker
    self._HandlePacket(pkt)
  File "/wyzesense2mqtt/wyzesense.py", line 375, in _HandlePacket
    handler(pkt)
  File "/wyzesense2mqtt/wyzesense.py", line 285, in _OnSensorAlarm
    sensor_type = "unknown (" + type + ")"
TypeError: can only concatenate str (not "int") to str
Sending PUBLISH (d0, q2, r1, m220), 'b'wyzesense2mqtt/status'', ... (6 bytes)
Received PUBREC (Mid: 220)
Sending PUBREL (Mid: 220)
```
The exception messages are not in any log files and can only be seen
from console output. To make it worse, when exception happens, the program
doesn't detect it so it continues running without realizing it.

This is just a temporary fix by avoiding the exception. A proper fix should
force the program to exit/crash to make similiar issues more visible.